[package]
name = "my-ibex-app"
version = "0.1.0"
edition = "2021"

[dependencies]
# ibex = { path = "../ibex/main" }
ibex = { git = "https://github.com/dxrcy/ibex" }
# ibex = { package = "ibex_alpha" }
